### ISSUE TITLE
implement better data storage for user settings

### ISSUE THREAD

**Issue by westwick** [megamind-mud/megamind-client#22]
Suggestion from ray: NeDB

**Comment by rayzorben** [comment]
NeDB I recommend for data in general. For user settings, lets identify the format. I prefer yaml because of the lack of curly braces for users who are not as advanced, combined with a schema to enforce it. 

If YAML is fine, I have a class that auto reloads and verifies schema against changes to a yaml file, we can use that.

Code example, called anywhere will always return a pointer to the same config for the same file.

```javascript
const config = new Configuration('filename.yaml', [arrayOfPathsToCheck], loadedCallback, errorCallback);
```

```yaml
paths:
  base: 'c:\sync\MegaMud' # Path to MegaMud directory, if left blank will use the current directory
  mega: 'ParaMegaMud.exe'
  proxy: 'MegaMegaMudProxy.exe'
  dll: 'c:\sync\MegaMegaMud\MegaMegaMud\MegaMegaMud.dll'
  debugScript: 'c:\sync\MegaMegaMud\proxy\proxy.js'

debugNode: true

ui:
  messageTimeMs: 5000 # time in milliseconds to display status messages

game:
  races:
    1: Human
```

Accessing (note will throw ESLint error since config.game does not exist on the class.
```javascript
const raceName = config.game.races[raceNum];
```
